deployment:
  image: <your container registry>/backend-common
  tag: 0.0.1
  user: 1000
name: common
ports: 
  port: 8080
  targetPort: 8080
resources:
  requests:
    cpu: 256m
    memory: 256Mi
  limits:
    cpu: 1024m
    memory: 2048Mi