apiVersion: v1
kind: Pod
metadata:
  name: busybox-demo
spec:
  serviceAccountName: deploy-prod-acc
  containers:
  - name: busybox-demo
    image: artifactory.axisb.com/corpomni-backend-docker-local/busybox/busybox:latest
    command: ["sleep"]
    args: ["1000000"]
  imagePullSecrets:
    - name: regcred
